import { SiteManifest } from '../types/manifest';

export interface TemplateDefinition {
  id: string;
  name: string;
  category: 'business' | 'services' | 'product';
  description: string;
  previewColor: string;
  icon: string;
  manifest: SiteManifest;
}

export const TEMPLATES: TemplateDefinition[] = [
  // 1. Business Template
  {
    id: 'template-business',
    name: 'شرکتی و نوآوری',
    category: 'business',
    description: 'مناسب شرکت‌های دانش‌بنیان، مهندسی، مشاوره مدیریت و بازرگانی',
    previewColor: '#f59e0b',
    icon: '🏢',
    manifest: {
      schemaVersion: 1,
      projectId: 'proj-business-demo',
      type: 'website',
      meta: {
        title: 'شرکت مهندسی فراز سازه | پیشرو در راهکارهای مهندسی',
        description: 'طراحی، اجرا و نظارت بر پروژه‌های صنعتی و زیرساختی با بالاترین استانداردهای جهانی',
        language: 'fa',
        rtl: true,
        author: 'Faraz Saze Co.',
      },
      theme: {
        primaryColor: '#f59e0b',
        accentColor: '#38bdf8',
        backgroundColor: '#090d16',
        textColor: '#f8fafc',
        cardBackground: '#111726',
        fontFamily: 'Vazirmatn',
        borderRadius: 'md',
        darkMode: true,
      },
      backend: 'none',
      settings: {
        smoothScroll: true,
        backToTop: true,
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      blocks: [
        {
          id: 'hero-1',
          type: 'hero',
          visible: true,
          badge: 'نوآوری در اجرا · استانداردهای بین‌المللی',
          title: 'مهندسی دقیق، ساخت پایدار برای فردا',
          subtitle: 'ارائه راهکارهای جامع مهندسی، طراحی سازه‌های صنعتی و بهینه‌سازی فرآیندهای تولید با همراهی متخصصان برجسته.',
          layout: 'split-right',
          imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
          ctaPrimary: {
            text: 'مشاوره و استعلام پروژه',
            link: '#contact',
          },
          ctaSecondary: {
            text: 'درباره قابلیت‌های ما',
            link: '#features',
          },
        },
        {
          id: 'features-1',
          type: 'features',
          visible: true,
          customId: 'features',
          title: 'چرا فراز سازه؟',
          subtitle: 'مزیت‌های رقابتی که تضمین‌کننده بهره‌وری و کیفیت پروژه‌های شما هستند',
          items: [
            {
              id: 'f-1',
              icon: '🛡️',
              title: 'استاندارد ایمنی و کیفیت',
              description: 'رعایت دقیق‌ترین آیین‌نامه‌ها و کنترل کیفیت چندمرحله‌ای در تمام فازها.',
            },
            {
              id: 'f-2',
              icon: '⚡',
              title: 'سرعت در تحویل و مدیریت زمان',
              description: 'بهره‌گیری از مدل‌سازی BIM و چابکی اجرایی برای تحویل بدون دیرکرد.',
            },
            {
              id: 'f-3',
              icon: '💎',
              title: 'تیم متخصص و دارای گواهینامه',
              description: 'کادری متشکل از مهندسان ارشد با سابقه ده‌ها پروژه ملی و بین‌المللی.',
            },
          ],
        },
        {
          id: 'about-1',
          type: 'about',
          visible: true,
          title: 'بیش از ۱۵ سال تجربه ساخت و توسعه',
          subtitle: 'همراه مطمئن صنایع پیشرو در تحول زیرساخت‌ها',
          content: 'شرکت مهندسی فراز سازه با تکیه بر دانش فنی روز و مدیریت یکپارچه مهندسی، از سال ۱۳۸۸ مجری صدها طرح عمرانی، صنعتی و تأسیساتی در سراسر کشور بوده است. هدف ما خلق ارزش بلندمدت و پایداری سازه‌ای است.',
          imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1000&auto=format&fit=crop',
          stats: [
            { id: 's-1', label: 'پروژه موفق', value: '+۱۴۰' },
            { id: 's-2', label: 'مهندس و کارشناس', value: '+۸۵' },
            { id: 's-3', label: 'استان تحت پوشش', value: '۲۴' },
            { id: 's-4', label: 'رضایت کارفرمایان', value: '۹۹٪' },
          ],
        },
        {
          id: 'testimonials-1',
          type: 'testimonials',
          visible: true,
          title: 'دیدگاه کارفرمایان',
          subtitle: 'آنچه شرکای تجاری ما درباره همکاری مشترک می‌گویند',
          items: [
            {
              id: 't-1',
              name: 'مهندس آرش کریمی',
              role: 'مدیرعامل پتروپویا',
              quote: 'دقت در جزییات و پایبندی به زمان‌بندی قرارداد در پروژه پالایشگاهی، فراز سازه را به شریک استراتژیک ما تبدیل کرد.',
              avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
              rating: 5,
            },
            {
              id: 't-2',
              name: 'دکتر مریم شمس',
              role: 'معاونت فنی هلدینگ رادین',
              quote: 'تیم مهندسی فراز سازه استانداردهایی فراتر از انتظار ارائه دادند و در بحران‌ها بهترین پاسخگویی را داشتند.',
              avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop',
              rating: 5,
            },
          ],
        },
        {
          id: 'contact-1',
          type: 'contact',
          visible: true,
          customId: 'contact',
          title: 'ارتباط مستقیم با دفتر مرکزی',
          subtitle: 'برای آغاز همکاری و دریافت پیشنهاد فنی، با ما در تماس باشید',
          phone: '۰۲۱-۸۸۹۹۰۰۱۱',
          email: 'info@farazsazeh.com',
          address: 'تهران، خیابان ولیعصر، نرسیده به میدان ونک، برج نگین، طبقه ۸',
          workingHours: 'شنبه تا چهارشنبه: ۸:۰۰ الی ۱۷:۰۰',
          showForm: true,
          formButtonText: 'ارسال درخواست مشاوره',
        },
        {
          id: 'footer-1',
          type: 'footer',
          visible: true,
          brandName: 'فراز سازه',
          description: 'پیشرو در مهندسی زیرساخت و فناوری‌های مدرن ساخت.',
          copyright: '© ۱۴۰۳ کلیه حقوق مادی و معنوی برای فراز سازه محفوظ است.',
          links: [
            { id: 'fl-1', title: 'درباره ما', url: '#about' },
            { id: 'fl-2', title: 'خدمات', url: '#features' },
            { id: 'fl-3', title: 'تماس با ما', url: '#contact' },
          ],
        },
      ],
    },
  },

  // 2. Services Template (تالار پذیرایی و تشریفات لوکس)
  {
    id: 'template-services',
    name: 'خدماتی و تشریفات',
    category: 'services',
    description: 'طراحی ویژه تالارهای پذیرایی، کلینیک‌ها، سالن‌های زیبایی و مجموعه‌های تشریفاتی',
    previewColor: '#ec4899',
    icon: '✨',
    manifest: {
      schemaVersion: 1,
      projectId: 'proj-services-demo',
      type: 'website',
      meta: {
        title: 'مجموعه تشریفات و تالار مجلل پالاس | شبی به‌یادماندنی',
        description: 'میزبانی باشکوه از مجالس، جشن‌های عروسی و همایش‌های شما با مجلل‌ترین عمارت و منوهای اختصاصی',
        language: 'fa',
        rtl: true,
        author: 'Palace Royal Event',
      },
      theme: {
        primaryColor: '#f59e0b',
        accentColor: '#fb7185',
        backgroundColor: '#0c0f14',
        textColor: '#fafaf9',
        cardBackground: '#171a21',
        fontFamily: 'Vazirmatn',
        borderRadius: 'lg',
        darkMode: true,
      },
      backend: 'none',
      settings: {
        smoothScroll: true,
        backToTop: true,
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      blocks: [
        {
          id: 'hero-srv',
          type: 'hero',
          visible: true,
          badge: 'شکوه و اصالت در میزبانی مجالس رویایی',
          title: 'خاطره‌انگیزترین شب زندگی شما در عمارت مجلل پالاس',
          subtitle: 'طراحی اختصاصی دکوراسیون، کترینگ بین‌المللی با سرآشپزان نامدار و نورپردازی رویایی در فضایی به وسعت ۳۰۰۰ مترمربع.',
          layout: 'centered',
          imageUrl: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=1200&auto=format&fit=crop',
          ctaPrimary: {
            text: 'رزرو بازدید حضوری',
            link: '#contact',
          },
          ctaSecondary: {
            text: 'مشاهده منوها و خدمات',
            link: '#services',
          },
        },
        {
          id: 'services-srv',
          type: 'services',
          visible: true,
          customId: 'services',
          title: 'خدمات اختصاصی تشریفات',
          subtitle: 'پکیج‌های همه‌جانبه برای خلق لحظاتی بدون دغدغه و باشکوه',
          items: [
            {
              id: 'srv-1',
              icon: '🍽️',
              title: 'کترینگ و شام VIP',
              description: 'انواع غذاهای اصیل ایرانی و بین‌المللی، بوفه سالاد و دسر تازه و نوشیدنی‌های طبیعی.',
              price: 'از نفری ۹۵۰ هزار تومان',
              badge: 'محبوب‌ترین',
            },
            {
              id: 'srv-2',
              icon: '💐',
              title: 'گل‌آرایی و دیزاین ژورنالی',
              description: 'دیزاین سفره عقد، ورودی عمارت و میزهای مهمانان با تازه‌ترین گل‌های فصل ارکیده و رز.',
              price: 'طراحی سفارشی',
            },
            {
              id: 'srv-3',
              icon: '🎶',
              title: 'سیستم صوتی و استیج نور داینامیک',
              description: 'حرفه‌ای‌ترین بند موسیقی زنده، اپراتور صدا و شوهای نوری مطابق با تم انتخابی شما.',
              price: 'پکیج کامل',
            },
          ],
        },
        {
          id: 'gallery-srv',
          type: 'gallery',
          visible: true,
          title: 'گوشه‌ای از فضای رویایی عمارت',
          subtitle: 'تصاویر واقعی از دکوراسیون، محوطه باغ و سالن‌های اختصاصی',
          items: [
            {
              id: 'g-1',
              title: 'سالن پذیرایی اصلی',
              caption: 'ظرفیت تا ۸۰۰ مهمان با سقف مرتفع و لوسترهای کریستال',
              imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=800&auto=format&fit=crop',
            },
            {
              id: 'g-2',
              title: 'جایگاه عقد در فضای باز باغ',
              caption: 'طراحی در کنار برکه اختصاصی و آلاچیق گل‌آرایی شده',
              imageUrl: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?q=80&w=800&auto=format&fit=crop',
            },
            {
              id: 'g-3',
              title: 'میز شام ویژه VIP',
              caption: 'پذیرایی با ظروف نقره و دیزاین شمع و کریستال',
              imageUrl: 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?q=80&w=800&auto=format&fit=crop',
            },
          ],
        },
        {
          id: 'faq-srv',
          type: 'faq',
          visible: true,
          title: 'پرسش‌های متداول مشتریان',
          subtitle: 'پاسخ به سوالات پرتکرار پیرامون نحوه رزرو و جزئیات برگزاری',
          items: [
            {
              id: 'faq-1',
              question: 'چقدر قبل از تاریخ مراسم باید تاریخ را رزرو کنیم؟',
              answer: 'با توجه به تقویم فشرده مجالس، پیشنهاد می‌کنیم حداقل ۳ الی ۶ ماه زودتر تاریخ مدنظرتان را قطعی نمایید.',
            },
            {
              id: 'faq-2',
              question: 'آیا امکان تست منوی غذا قبل از عقد قرارداد وجود دارد؟',
              answer: 'بله، هر هفته در روزهای پنجشنبه مراسم تست زنده منوی شام برای زوج‌های متقاضی با هماهنگی قبلی برگزار می‌شود.',
            },
            {
              id: 'faq-3',
              question: 'ظرفیت پارکینگ اختصاصی مجموعه چقدر است؟',
              answer: 'مجموعه دارای پارکینگ سرپوشیده و اختصاصی با ظرفیت ۲۵۰ خودرو و همراهی کادر والِت است.',
            },
          ],
        },
        {
          id: 'contact-srv',
          type: 'contact',
          visible: true,
          customId: 'contact',
          title: 'هماهنگی بازدید حضوری',
          subtitle: 'مشاوران ما آماده پاسخگویی و ارائه مشاوره‌های جامع به شما هستند',
          phone: '۰۲۱-۲۲۰۰۳۳۴۴',
          email: 'booking@palace-royal.ir',
          address: 'تهران، ابتدای جاده لواسان، بلوار گلستان، عمارت مجلل پالاس',
          workingHours: 'همه روزه از ساعت ۱۰:۰۰ تا ۲۱:۰۰',
          showForm: true,
          formButtonText: 'ثبت درخواست بازدید',
        },
        {
          id: 'footer-srv',
          type: 'footer',
          visible: true,
          brandName: 'عمارت پالاس',
          description: 'لوکس‌ترین تجربه برگزاری جشن‌ها و رویدادهای فراموش‌نشدنی.',
          copyright: '© ۱۴۰۳ تمامی حقوق محفوظ است.',
          links: [
            { id: 'f-1', title: 'خدمات تشریفات', url: '#services' },
            { id: 'f-2', title: 'گالری تصاویر', url: '#gallery' },
            { id: 'f-3', title: 'رزرو بازدید', url: '#contact' },
          ],
        },
      ],
    },
  },

  // 3. Product & Portfolio Template
  {
    id: 'template-product',
    name: 'محصول و نمونه‌کار',
    category: 'product',
    description: 'برای استودیوهای خلاق، سازندگان نرم‌افزار، محصولات دیجیتال و فریلنسرها',
    previewColor: '#38bdf8',
    icon: '🚀',
    manifest: {
      schemaVersion: 1,
      projectId: 'proj-product-demo',
      type: 'website',
      meta: {
        title: 'استودیو طراحی محصول نِکست | طراحی تجربیات دیجیتال',
        description: 'ما ایده‌های خام را به رابط‌های کاربری چشم‌نواز و محصولات نرم‌افزاری کاربردی تبدیل می‌کنیم.',
        language: 'fa',
        rtl: true,
        author: 'Next Product Studio',
      },
      theme: {
        primaryColor: '#0ea5e9',
        accentColor: '#f59e0b',
        backgroundColor: '#0a0d14',
        textColor: '#f1f5f9',
        cardBackground: '#131926',
        fontFamily: 'Vazirmatn',
        borderRadius: 'md',
        darkMode: true,
      },
      backend: 'none',
      settings: {
        smoothScroll: true,
        backToTop: true,
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      blocks: [
        {
          id: 'hero-prod',
          type: 'hero',
          visible: true,
          badge: 'استودیو دیزاین محصول · نسل جدید',
          title: 'ما برای استارتاپ‌ها محصولات ماندگار خلق می‌کنیم',
          subtitle: 'ترکیبی از استراتژی محصول، طراحی رابط کاربری (UI/UX) و ساخت نمونه‌های اولیه تعاملی با سرعت بالا.',
          layout: 'centered',
          ctaPrimary: {
            text: 'مشاهده پلن‌های همکاری',
            link: '#pricing',
          },
          ctaSecondary: {
            text: 'نمونه پروژه‌های ما',
            link: '#features',
          },
        },
        {
          id: 'features-prod',
          type: 'features',
          visible: true,
          customId: 'features',
          title: 'اصول کار ما',
          subtitle: 'تمرکز بر حل مسائل واقعی با طراحی معنادار و بدون زوائد',
          items: [
            {
              id: 'fp-1',
              icon: '🎯',
              title: 'طراحی مبتنی بر داده و رفتار کاربر',
              description: 'تصمیم‌گیری بر مبنای تست‌های کاربردی واقعی، نه صرفاً حدس و گمان.',
            },
            {
              id: 'fp-2',
              icon: '⚡',
              title: 'تحویل چابک و اسپرینت‌های هفتگی',
              description: 'مشاهده پیشرفت گام‌به‌گام در محیط‌های تستی و مشارکت مداوم شما.',
            },
            {
              id: 'fp-3',
              icon: '🎨',
              title: 'سیستم دیزاین مقیاس‌پذیر',
              description: 'ساخت کامپوننت‌های پایدار برای تسهیل توسعه فنی در تیم مهندسی شما.',
            },
          ],
        },
        {
          id: 'pricing-prod',
          type: 'pricing',
          visible: true,
          customId: 'pricing',
          title: 'پلن‌های همکاری منعطف',
          subtitle: 'متناسب با نیاز تیم‌های نوپا تا شرکت‌های مقیاس‌یافته',
          items: [
            {
              id: 'p-1',
              name: 'اسپرینت MVP',
              price: '۲۵ میلیون تومان',
              period: 'تحویل ۲ هفته‌ای',
              description: 'مناسب اعتبارسنجی ایده و ساخت اولین نسخه تست بازار',
              features: [
                'طراحی وایرفریم و جریان کاربر',
                'دیزاین کامل صفحات اصلی',
                'پروتوتایپ تعاملی فیگما',
                'یک دور بازبینی رایگان',
              ],
              ctaText: 'انتخاب این پلن',
              ctaLink: '#contact',
            },
            {
              id: 'p-2',
              name: 'طراحی جامع محصول',
              price: '۵۵ میلیون تومان',
              period: 'تحویل ۴ هفته‌ای',
              highlighted: true,
              badge: 'پیشنهاد ما',
              description: 'پکیج کامل UI/UX و سیستم دیزاین یکپارچه',
              features: [
                'تحقیقات بازار و پرسونای مشتری',
                'سیستم دیزاین کامل (Design System)',
                'طراحی واکنش‌گرا موبایل و وب',
                'راهنمای تحویل به برنامه‌نویسان',
                'پشتیبانی ۱ ماهه حین پیاده‌سازی',
              ],
              ctaText: 'شروع همکاری',
              ctaLink: '#contact',
            },
          ],
        },
        {
          id: 'cta-prod',
          type: 'cta',
          visible: true,
          badge: 'پروژه‌ای در ذهن دارید؟',
          title: 'بیایید با هم محصول بعدی‌تان را بسازیم',
          subtitle: 'یک جلسه آنلاین ۳۰ دقیقه‌ای بدون هزینه برای بررسی ابعاد فنی و طراحی ایده‌تان.',
          buttonText: 'رزرو جلسه همفکری',
          buttonLink: '#contact',
        },
        {
          id: 'contact-prod',
          type: 'contact',
          visible: true,
          customId: 'contact',
          title: 'ارتباط با استودیو نکست',
          subtitle: 'پاسخ ما ظرف کمتر از ۲۴ ساعت کاری ارسال خواهد شد',
          email: 'hello@nextstudio.io',
          phone: '۰۲۱-۴۴۵۵۶۶۷۷',
          showForm: true,
          formButtonText: 'ارسال خلاصه پروژه',
        },
        {
          id: 'footer-prod',
          type: 'footer',
          visible: true,
          brandName: 'استودیو نکست',
          description: 'خلق تجربیات دیجیتال کاربردی و استاندارد.',
          copyright: '© ۲۰۲۶ Next Design Studio. تمامی حقوق محفوظ است.',
          links: [
            { id: 'lp-1', title: 'اصول ما', url: '#features' },
            { id: 'lp-2', title: 'پلن‌ها', url: '#pricing' },
            { id: 'lp-3', title: 'تماس', url: '#contact' },
          ],
        },
      ],
    },
  },
];
